name: Deploy project
on: [push, workflow_dispatch]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout
      - name: Linting
        run: npm run eslint --ext .jsx --fix src
  tests:
    needs: CodeLinting
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test